### PR TITLE
Update 3.7.13

### PR DESCRIPTION
**Pull request by Arishamays1**
# Update for `3.7.13` with CVE Patch
Jira [ticket](https://anaconda.atlassian.net/browse/PKG-416?atlOrigin=eyJpIjoiYTRjNWUyZjhmM2ZlNDc5Njk1NWMzZWZlNGM0ZTM5YTMiLCJwIjoiaiJ9)

- added mailcap CVE [patch](https://github.com/advisories/GHSA-wvcr-2gc8-63gg). The patch is the merge commit from [this PR](https://github.com/python/cpython/pull/91993), which was the one that was accepted to fix the [issue](https://github.com/python/cpython/issues/68966)
- made amendments to `build.sh` for `linux-ppc64le` optimization

### CODE REVIEW

**Review by varlackc — COMMENTED** [review]
There seems to be a redirect on the `dev_url` to the following URL:

https://devguide.python.org/

**Review by danpetry — COMMENTED** [review]
LGTM - two minor nits but good to go

**Comment by skupr-anaconda** [comment]
The patch seems to be fine.

**Review by danpetry — APPROVED** [review]

**Comment by danpetry** [comment]
Prefect seems to be unstable, both win-64 and linux-64 I have seen passing before.

**Pull request merged**
