### PR TITLE
PKG-1060 Fix branding 3.11

### PR DESCRIPTION
**Pull request by Jrice1317**
**Jira:** [PKG-1060](https://anaconda.atlassian.net/browse/PKG-1060)

**Updates:**
- bumped build number
- Changed message to: "packaged by Anaconda, Inc."

### CODE REVIEW

**Review by pseudoyim — APPROVED** [review]
LGTM Thanks!

**Review by varlackc — COMMENTED** [review]
Not sure if we still need the patch in `line 76` for the patch `0016` for `cross compiling in osx`

https://github.com/AnacondaRecipes/python-feedstock/blob/9346b2ac0f3eb0db97c07bd2c98bd1820985e5ad/recipe/meta.yaml#L76

Other than that everything else looks good.

**Review by cbouss — APPROVED** [review]
LGTM

**Comment by cbouss** [comment]
> Not sure if we still need the patch in `line 76` for the patch `0016` for `cross compiling in osx`
> 
> https://github.com/AnacondaRecipes/python-feedstock/blob/9346b2ac0f3eb0db97c07bd2c98bd1820985e5ad/recipe/meta.yaml#L76
> 
> Other than that everything else looks good.

It doesn't seem to be something we need. That being said, I'd prefer to be conservative and only change what is needed (branding) like it is now.

**Pull request merged**
