### PR TITLE
V3.11.9

### PR DESCRIPTION
**Pull request by SC426**
python 3.11.9

**Destination channel:** defaults

### Links

- [PKG-4393](https://anaconda.atlassian.net/browse/PKG-4393) 
- [Upstream repository](https://www.python.org/downloads/release/python-3119/)
- [Upstream changelog/diff](https://docs.python.org/release/3.11.9/whatsnew/changelog.html#python-3-11-9)

### Explanation of changes:

- Update version
- Update `sqlite` to `3.45.1`

[PKG-4393]: https://anaconda.atlassian.net/browse/PKG-4393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by cbouss — APPROVED** [review]
LGTM!

**Review by skupr-anaconda — APPROVED** [review]
LGTM but should we rebuild it after [expat 2.6.2](https://github.com/AnacondaRecipes/expat-feedstock/pull/12) will be available on defaults?

**Review by JamesRobertsonGames — APPROVED** [review]
Looks good to me! :+1:

**Comment by skupr-anaconda** [comment]
@SC426 expat is a host dependency. As `expat 2.6.2` is available on defaults it would be nice to close/reopen the PR.

**Comment by JeanChristopheMorinPerso** [comment]
@skupr-anaconda where you see expat? I can't find any reference to expat...

**Comment by skupr-anaconda** [comment]
Sorry, it's unvendored in v.3.12 (in the #141 PR141). Ignore my comment for this PR

**Pull request merged**
