### PR TITLE
update to 3.10.0

### PR DESCRIPTION
**Pull request by katietz**

### CODE REVIEW

**Comment by dbast** [comment]
@katietz Yes... we do something that influences the build outcome quality... that has to be part of the git history... so that we know the conditions under which a resulting package was created... if we later want to rebuild the package with tests enabled, then we remove the file... and again the rebuild then has a build_number +=1 and a proper git history that tells how it was created...

**Comment by katietz** [comment]
Hmm, I am not so happy about this file here ... as the testing can be still done with package, but timely rescheduled.  Also this is  a pretty good sample why such a package shouldn't be blindly uploaded to defaults, but needs to be available for further testing, when all required dependencies are present.
This file is a kludge

**Comment by mbargull** [comment]
> Ok the PR is merged now... lots of content (+1,565 −1,474) in almost one commit only... it squashes lots of small commits that are also present on https://github.com/conda-forge/python-feedstock mostly done bei Isuruf. Would have been nice to see a merge commit or cherry-picked commits + the stuff we do additionally on top via commits... that would have been much easier to review.

+1. And Isuru (and others) has put considerable amount of work into this which is worth crediting.

(And BTW, https://github.com/conda-forge/python-feedstock/compare/master...AnacondaRecipes:master shows some more divergences which could make sense to address in some future rebuild/patch version update.)

**Comment by katietz** [comment]
Not sure what you mean here?  I sychronized package, before it landed on conda-forge.  So that there are still some differences are likely.  I had to, as our Product wanted to get an early version .... Most changesd were actually reviewed by me, and not all of CF decissions are actual something I could share. Especially the runtime-dependency stuff is looking a bit backweard. Of course the  changes are work of many, by lead of Isuruf on CF.
Which differences you mean here in detail?  I would be interested to  discuss those in detail

**Comment by mbargull** [comment]
> ... not all of CF decissions are actual something I could share. Especially the runtime-dependency ...

> Which differences you mean here in detail? I would be interested to discuss those in detail

It's mostly the de-vendoring. Other than that, I can only recall macOS cross-platform build support (for building ARM on x86) -- but the latter is probably not much relevant for you since I don't believe use cross compile for macOS.

**Pull request merged**
